# general configuration
url: "http://raghavsub.com"
baseurl: ""

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/headshot.png"
  # author will appear under the avatar (optional)
  author: "Raghav Subramaniam"
  # tagline will appear under the title (optional)
  # tagline: ""
  # twitter @username (as defined by the twitter card specs)
  twitter: "raghavsub"

# exclude
exclude: ["vendor", "CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# dependencies
markdown: kramdown
highlighter: rouge

# permalinks
permalink: pretty
